Craft/Controllers/BeersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Craft.Models;
using Craft.Models.Craft;
using Microsoft.AspNet.Identity;

namespace Craft.Controllers
{
    public class BeersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Beers
        public ActionResult Index()
        {
            return View(db.Beers.ToList());
        }

        
        public ActionResult BeerList()
        {
            List<Beer> BeerList = db.Beers.ToList();
            List<Distributor> distributors = db.Distributors.ToList();
            List<Distributor_Beer> distributor_beer = db.Distributor_Beers.ToList();
            List<Beer> DistBeerList = new List<Beer>();
            List<Favorite> Fav = new List<Favorite>();
            List<int> BeerIds = new List<int>();
            var currentUserId = User.Identity.GetUserId();
            var currentDist = (from d in distributors where d.UserId == currentUserId select d.DistributorId).FirstOrDefault();
            for (int i = 0; i < distributor_beer.Count; i++)
            {
                if(distributor_beer[i].DistributorId == currentDist)
                {
                    BeerIds.Add(distributor_beer[i].BeerId);
                }
            }
            for (int h = 0; h < BeerList.Count; h++)
            {
                for (int j = 0; j < BeerIds.Count; j++)
                {
                    if(BeerIds[j] == BeerList[h].BeerId)
                    {
                        var Id = BeerList[h].BeerId;
                        Fav = db.Favorites.Where(x => x.BeerId == Id).ToList();
                        BeerList[h].Favorite = Fav.Count;
                        DistBeerList.Add(BeerList[h]);

                    }
                }
            }
            
            return View(DistBeerList);
        }

        public ActionResult NewReleases()
        {
            List<Beer> NewBeer = db.Beers.Where(x => x.NewRelease == true).ToList();
            return View(NewBeer);
        }

        // GET: Beers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Beer beer = db.Beers.Find(id);
            if (beer == null)
            {
                return HttpNotFound();
            }
            return View(beer);
        }

        // GET: Beers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Beers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BeerName,BeerId,Description,Type,ABV,NewRelease")] Beer beer)
        {
            List<Distributor> AllDistributors = db.Distributors.ToList();
            string currentUserId = User.Identity.GetUserId();
            Distributor currentDistributor = (from x in AllDistributors where x.UserId == currentUserId select x).FirstOrDefault();
            Distributor_Beer distributor_beer = new Distributor_Beer();
            if (ModelState.IsValid)
            {
                db.Beers.Add(beer);
                db.SaveChanges();
                distributor_beer.BeerId = beer.BeerId;
                distributor_beer.DistributorId = currentDistributor.DistributorId;
                db.Distributor_Beers.Add(distributor_beer);
                db.SaveChanges();
                return RedirectToAction("BeerList");
            }

            return View(beer);
        }

        // GET: Beers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Beer beer = db.Beers.Find(id);
            if (beer == null)
            {
                return HttpNotFound();
            }
            return View(beer);
        }

        // POST: Beers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BeerName,BeerId,Description,Type,ABV,NewRelease")] Beer beer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(beer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("BeerList");
            }
            return View(beer);
        }

        // GET: Beers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Beer beer = db.Beers.Find(id);
            if (beer == null)
            {
                return HttpNotFound();
            }
            return View(beer);
        }

        // POST: Beers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Beer beer = db.Beers.Find(id);
            db.Beers.Remove(beer);
            db.SaveChanges();
            return RedirectToAction("BeerList");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Craft/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CRAFT</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CRAFT", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    @if (User.IsInRole("Customer"))
                    {
                        <li>@Html.ActionLink("Favorite Beers", "AddToFavorites", "Favorites")</li>
                        <li>@Html.ActionLink("Bar Search", "ChooseBeer", "Bars")</li>
                        <li>@Html.ActionLink("New Releases", "NewReleases", "Beers")</li>
                    }
                    @if (User.IsInRole("Distributor"))
                    {
                        <li>@Html.ActionLink("Beer List", "BeerList", "Beers")</li>
                        <li>@Html.ActionLink("Bar List", "BarList", "Bars")</li>
                        
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - KLEBBA Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>